server:
  port: 9000
spring:
  rabbitmq:
    addresses: localhost:5672
    host: localhost
    port: 15672
    username: rabbitmq
    password: rabbitmq
  cloud:
    stream:
      bindings:
        output:
          destination: events-exchange
          content-type: application/json
logging:
  level:
    org:
      springframework: DEBUG